### ISSUE TITLE
Workflow for sending invitations to existing users is convoluted

### ISSUE THREAD

**Issue by asmecher** [craft-oa/ui-library#20]
When a journal manager wants to send an invitation to an existing user, it'll be logical for them to find the user's profile, hit an Edit link (or similar), and expect the changes they want to be possible there.

Currently, that flow would have the manager editing the user's account directly, per the old "manager can edit directly" workflow. That possibility should be removed before 3.5 is released in favour of invitations.

However, the only path that's currently possible in the open PRs (unless I missed it) is to "Invite to a role" by the Invitations list directly. That's not an intuitive place to find the feature for a user who's already in the list just below.

From Devika:
> Clicking on "Add Another Role" would allow them to choose from a dropdown menu, and then an email would be sent. If it's easier to understand, it's similar to what you see when you click on "View" under user invitations. Alternatively, you can click "Invite to a Role" and search by email ID if searching through the list feels too cumbersome. The user profile will then appear with an indicator.

**Comment by Devika008** [comment]
Hello,

Here's a quick prototype based on my initial specs. Since users are entering their own information, we shouldn't allow edits to that data to maintain user responsibility (as discussed earlier). The editor's role should be limited to inviting the user to a new role. Most users appreciated that their information couldn't be edited by others, but a few wanted the ability to make changes. A simple solution would be to use the "Login As" feature to update the info, or we could add a "Request to Change Information" button that sends an email prompting the user to update their personal details.

https://youtu.be/zJfdrkiXKnY

On figma the screens can be found here: 
1. https://www.figma.com/design/Wf7sDlUg2372jaKKTJ0Mgz/OJS-3.4-3.5?node-id=3052-7120&t=BXWrTy6KrQhkTiYx-4
2. https://www.figma.com/design/Wf7sDlUg2372jaKKTJ0Mgz/OJS-3.4-3.5?node-id=8227-19482&t=BXWrTy6KrQhkTiYx-4
3. https://www.figma.com/design/Wf7sDlUg2372jaKKTJ0Mgz/OJS-3.4-3.5?node-id=8227-19707&t=BXWrTy6KrQhkTiYx-4

Its also in the notes on NextCloud for user invitation: https://nextcloud.publicknowledgeproject.org/s/yAs6HwYAPD5jMEy
