### ISSUE TITLE
invitation table -> edit  -> invitation   add new roles -> save and continue error if there is an already existing user has a wrong start date

### ISSUE THREAD

**Issue by withanage** [craft-oa/ui-library#34]
[Screencast from 26.09.2024 10:19:58.webm](https://github.com/user-attachments/assets/37fe0c30-8699-400b-b80e-7a5a252c9e0d)

**Comment by ipula** [comment]
this should be fix from backend side. Issue is start date in the already invited role has a previous date.

**Comment by defstat** [comment]
@ipula there is a validation error that checks whether the start date of a role assignment is a "future" date - So if you try to add a user role with a past date, the invitation complains, returning the validation error that you are showing. 

When the invitation is accepted, the date assigned to the UserUserGroup is the one defined by the Inviter, even if this is a past date. Here we could implement it differently, assigning the `now` date for the new userUserGroup, if the invitation defined date is an already past one.

This is implemented this way so that the dispatched invitation does not have a past date for userUserGroup attached to it.
